[package]
name = "netcup"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.7", features = ["derive"] }
reqwest = {version="0.11.18", features = ["blocking","json"]}
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
